# 基础镜像：带 rviz/rviz_plugin 的 ROS1 Melodic 全家桶
FROM osrf/ros:melodic-desktop-full

ENV DEBIAN_FRONTEND=noninteractive

# 安装依赖，并配置ROS环境
# gedit: 图形文本编辑器，用于在GUI环境中编辑文件
# x11-apps: X11应用程序包，包含xeyes等X11测试工具
# mesa-utils: Mesa图形工具，包含glxgears等OpenGL测试程序
# dbus-x11: D-Bus X11支持
# echo source: 将ROS环境初始化脚本添加到bash配置中
# rm -rf: 清理apt缓存文件以减小镜像大小
# rosdep: ROS依赖管理工具
# libarmadillo-dev: Armadillo C++线性代数库 - Btraj 依赖
RUN apt-get update && apt-get install -y \
    gedit x11-apps mesa-utils dbus-x11 \
    libarmadillo-dev \
    nano vim tree curl \
    python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential \
    && echo "source /opt/ros/melodic/setup.bash" >> /root/.bashrc \
    && rosdep init || true \
    && rosdep update || true \
    && rm -rf /var/lib/apt/lists/*

# 安装 ripgrep
RUN curl -LO https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep_14.1.1-1_amd64.deb \
    && dpkg -i ripgrep_14.1.1-1_amd64.deb \
    && rm ripgrep_14.1.1-1_amd64.deb
# 设置彩色提示符
RUN echo "PS1='\\[\\e[1;35m\\]\\u@\\h\\[\\e[0;37m\\]:\\[\\e[1;33m\\]\\w\\$\\[\\e[0m\\] '" >> /root/.bashrc
# 工作目录
WORKDIR /root/catkin_ws

# 启动容器时默认执行的命令
CMD ["bash"]
